### ISSUE TITLE
notString expected values seem incorrect

### ISSUE THREAD

**Issue by dkrusch** [omariio/nodingbat#12]
When I did the notString exercise I coded the function based on the comments, but when I ran it the expected values weren't what I expected. I compared the values with coding bat and they are not the same. 

![screen shot 2016-05-23 at 10 10 28 am](https://cloud.githubusercontent.com/assets/16541781/15473736/8b4a44ae-20cf-11e6-968b-81c3af9837c3.png)

![untitled](https://cloud.githubusercontent.com/assets/16541781/15473777/b6aae16c-20cf-11e6-8545-b3a37faa3862.png)

**Comment by mfukano** [comment]
Your "if" condition is missing a space, so it won't grab the "not " that your substring is checking for.

**Comment by jessamynsmith** [comment]
Does the question spec look correct to you, @mfukano? E.g. when I look at the codingbat problem, it says the expected output when called with 'x' is 'not x', but the nodingbat problem says the expected output is 'x'.

**Comment by mfukano** [comment]
@jessamynsmith On closer examination, you're correct: the expected outputs for Nodingbat are indeed out of sync with Codingbat. 
In looking at the Codingbat specifications, one is only supposed to add "not" when the string itself is not detected.
![screen shot 2016-05-23 at 2 00 05 pm](https://cloud.githubusercontent.com/assets/5641347/15484471/09075674-20ef-11e6-903b-b82e4104e2b5.png)

However, the specifications on Nodingbat seem to be out of line; the solution for x, not bad, bad, not, and no need their expected outputs to be corrected, and the parsing for the string 'not' (solutions line 5) also seems to identify the substring incorrectly 
![screen shot 2016-05-23 at 1 59 59 pm](https://cloud.githubusercontent.com/assets/5641347/15484509/3cc98996-20ef-11e6-8388-ba1e79bc268f.png)

**Comment by MichaelFlops** [comment]
Nice work everyone, I just came up with a possible solution
![screen shot 2016-05-23 at 2 07 23 pm](https://cloud.githubusercontent.com/assets/7332836/15484677/fd800818-20ef-11e6-9afc-e42729cd125c.png)

Now I can push this to the main site but first if any of you have a better solution then we can put that in place instead. 

Also not when you believe you've found a broken problem on the live site< I suggest cloning this repo and checking out the solutions.js folder and submitting a PR... it would make my day!

**Comment by jessamynsmith** [comment]
@MichaelFlops Just about half an hour ago I forked and cloned and I am now trying to run it locally. You can expect PRs in future! :)

I'm not sure if the solution is supposed to be case-insensitive or not; codingbat isn't clear. It's also unclear what should happen in the case of null or empty string. Here is the solution I have been experimenting with:

```
var notString=function(str) {
  if (str === null || str === undefined || str.substring(0,3) == "not") {
    return str;
  }
  return "not " + str;
}
```

**Comment by jessamynsmith** [comment]
Let me also take this opportunity to say how delighted I am about this project! I do a lot of teaching and mentoring and I find students love codingbat. I'm so very happy to have an open-source equivalent.

**Comment by MichaelFlops** [comment]
@jessamynsmith Awesome! Your solution should be used because it factors in null/undefined. I won't touch it and in your PR you can even change the wording of the problem that the user sees in the /lib/setup.js file :)

Also if you would like an invite to our slack we are at omari.slack.com

I have some features that would make this project so much sweeter- it's a fun break from work and I'd love to improve it in these upcoming months. Thanks so much for the help! I would love for this to actually be useful to new students to coding.

**Comment by jessamynsmith** [comment]
Please do add me to slack!

**Comment by MichaelFlops** [comment]
@jessamynsmith Thanks so much! Sorry I had a busy work week, what is your email you use for slack, I'll send an invite!

**Comment by jessamynsmith** [comment]
I don't want to put it on github. If you tweet at me I'll DM you. https://twitter.com/jessamynsmith
