### ISSUE TITLE
Bad return value

### ISSUE THREAD

**Issue by examinedliving** [omariio/nodingbat#7]
I'm on iPad, and I will attach a screenshot since I can't copy and paste.  Unless I'm missing something fundamental, this should be a correct answer.  When I run the code with an alert, the values appear correct, but returning produces the following; (tried various iterations of what's below, with same result);

![image](https://cloud.githubusercontent.com/assets/3099093/11873445/90f26164-a4a8-11e5-99f3-b352c6d125e3.jpeg)

**Comment by MichaelFlops** [comment]
Thanks, it's been fixed in the repo.
